# Generated by Django 4.2.7 on 2023-11-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('uid', models.IntegerField()),
            ],
        ),
    ]
