# Generated by Django 4.2.7 on 2023-11-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_remove_task_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(max_length=50),
        ),
    ]
